import { App, Notice, TFile } from 'obsidian';
import { TubescribeSettings, SyncResult, TemplateVariables, VideoMetadata } from './types';
import { resolveYtdlpPath, fetchPlaylistMetadata, fetchVideoMetadata, downloadTranscript } from './ytdlp';
import { parseVTT, formatTranscript, formatTranscriptRaw } from './vtt-parser';
import { loadTemplate, renderTemplate, generateFilename, buildRenderVariables, formatDuration, formatDate } from './template';

function sleep(ms: number): Promise<void> {
	return new Promise((resolve) => setTimeout(resolve, ms));
}

function extractPlaylistId(url: string): string | null {
	const match = url.match(/[?&]list=([A-Za-z0-9_-]+)/);
	return match ? match[1] : null;
}

function todayDate(): string {
	return new Date().toISOString().split('T')[0];
}

export class SyncEngine {
	private app: App;
	private settings: TubescribeSettings;

	constructor(app: App, settings: TubescribeSettings) {
		this.app = app;
		this.settings = settings;
	}

	async run(): Promise<SyncResult> {
		const result: SyncResult = { created: 0, skipped: 0, errors: 0, errorDetails: [] };

		// 1. Resolve yt-dlp
		let binaryPath: string;
		try {
			binaryPath = await resolveYtdlpPath(this.settings.ytdlpPath);
		} catch (e) {
			throw new Error(`yt-dlp not found: ${e instanceof Error ? e.message : String(e)}`);
		}

		// 2. Filter enabled playlists
		const playlists = this.settings.playlists.filter((p) => p.enabled);
		if (playlists.length === 0) {
			new Notice('TubeScribe: No enabled playlists configured.');
			return result;
		}

		// 3. Ensure output folder exists
		const outputFolder = this.settings.outputFolder;
		try {
			const folderExists = await this.app.vault.adapter.exists(outputFolder);
			if (!folderExists) {
				await this.app.vault.createFolder(outputFolder);
			}
		} catch {
			// Folder might already exist, that's fine
		}

		// 4. Scan existing notes for video_id
		const existingIds = this.scanExistingVideoIds();

		// 5. Load template
		const template = await loadTemplate(this.app, this.settings.templatePath);

		// 6. Process each playlist
		const languages = this.settings.preferredLanguages
			.split(',')
			.map((l) => l.trim())
			.filter((l) => l.length > 0);

		for (const playlist of playlists) {
			const playlistId = extractPlaylistId(playlist.url);
			if (!playlistId) {
				new Notice(`TubeScribe: Invalid playlist URL for "${playlist.name}"`);
				result.errors++;
				result.errorDetails.push(`Invalid URL: ${playlist.url}`);
				continue;
			}

			let videos: VideoMetadata[];
			try {
				videos = await fetchPlaylistMetadata(binaryPath, playlist.url);
			} catch (e) {
				const msg = `Failed to fetch playlist "${playlist.name}": ${e instanceof Error ? e.message : String(e)}`;
				new Notice(`TubeScribe: ${msg}`);
				result.errors++;
				result.errorDetails.push(msg);
				continue;
			}

			// Filter to new videos
			const newVideos = videos.filter((v) => !existingIds.has(v.id));
			const totalNew = newVideos.length;
			const totalExisting = videos.length - totalNew;

			if (totalNew === 0) {
				new Notice(`TubeScribe: ${playlist.name} — all ${videos.length} videos already synced.`);
				continue;
			}

			new Notice(`TubeScribe: ${playlist.name} — ${totalNew} new video(s) found.`);

			// Determine output folder (with optional playlist subfolder)
			let playlistFolder = outputFolder;
			if (this.settings.groupByPlaylist && playlist.name) {
				const safeName = playlist.name.replace(/[/\\:*?"<>|]/g, '-').trim();
				playlistFolder = `${outputFolder}/${safeName}`;
				try {
					const subExists = await this.app.vault.adapter.exists(playlistFolder);
					if (!subExists) {
						await this.app.vault.createFolder(playlistFolder);
					}
				} catch {
					// Folder may already exist
				}
			}

			// Process each new video
			for (let i = 0; i < newVideos.length; i++) {
				const video = newVideos[i];

				try {
					// Progress notice
					new Notice(
						`TubeScribe: ${playlist.name} ${i + 1}/${totalNew} — ${video.title}`,
						3000
					);

					// Fetch full metadata
					let fullMeta: VideoMetadata;
					try {
						fullMeta = await fetchVideoMetadata(binaryPath, video.id);
					} catch {
						// Fall back to the basic metadata from playlist fetch
						fullMeta = video;
					}

					// Download transcript
					const vttContent = await downloadTranscript(
						binaryPath,
						fullMeta.url,
						languages,
						this.settings.includeAutoGenerated
					);

					const hasTranscript = vttContent !== null;

					if (!hasTranscript && !this.settings.createNoteWithoutTranscript) {
						result.skipped++;
						continue;
					}

					// Parse and format transcript
					let transcriptFormatted = '';
					let transcriptRaw = '';

					if (hasTranscript && vttContent) {
						const segments = parseVTT(vttContent);
						transcriptFormatted = formatTranscript(
							segments,
							this.settings.timestampFormat
						);
						transcriptRaw = formatTranscriptRaw(segments);
					} else {
						transcriptFormatted = '*No transcript available for this video.*';
						transcriptRaw = '';
					}

					// Build template variables
					const vars: TemplateVariables = {
						title: fullMeta.title,
						channel: fullMeta.uploader || 'Unknown',
						channel_url: fullMeta.channel_url || '',
						url: fullMeta.url,
						video_id: fullMeta.id,
						published: formatDate(fullMeta.upload_date),
						synced: todayDate(),
						duration: formatDuration(fullMeta.duration),
						playlist: playlist.name,
						description: fullMeta.description || '',
						has_transcript: String(hasTranscript),
						transcript: transcriptFormatted,
						transcript_raw: transcriptRaw,
					};

					// Build render variables with YAML-safe versions
					const renderVars = buildRenderVariables(vars);

					// Render note content
					const noteContent = renderTemplate(template, renderVars);

					// Generate filename and handle collisions
					const filename = generateFilename(
						this.settings.filenameFormat,
						renderVars
					);
					const filePath = await this.resolveFilePath(playlistFolder, filename);

					// Create the note
					await this.app.vault.create(filePath, noteContent);

					// Track this video as synced
					existingIds.add(fullMeta.id);
					result.created++;
				} catch (e) {
					const msg = `Error syncing "${video.title}": ${e instanceof Error ? e.message : String(e)}`;
					console.error('TubeScribe:', msg);
					result.errors++;
					result.errorDetails.push(msg);
				}

				// Rate limiting delay (skip after last video)
				if (i < newVideos.length - 1) {
					await sleep(1500);
				}
			}
		}

		return result;
	}

	/**
	 * Scan the output folder for existing video_id values in frontmatter.
	 */
	private scanExistingVideoIds(): Set<string> {
		const ids = new Set<string>();
		const outputFolder = this.settings.outputFolder;

		const files = this.app.vault.getMarkdownFiles();
		for (const file of files) {
			if (!file.path.startsWith(outputFolder)) continue;

			const cache = this.app.metadataCache.getFileCache(file);
			const videoId = cache?.frontmatter?.video_id;
			if (videoId) {
				ids.add(String(videoId));
			}
		}

		return ids;
	}

	/**
	 * Resolve a file path, handling collisions by appending (2), (3), etc.
	 */
	private async resolveFilePath(
		folder: string,
		filename: string
	): Promise<string> {
		const basePath = `${folder}/${filename}`;

		const exists = await this.app.vault.adapter.exists(basePath);
		if (!exists) return basePath;

		const nameWithoutExt = filename.replace(/\.md$/, '');
		for (let i = 2; i <= 99; i++) {
			const candidate = `${folder}/${nameWithoutExt} (${i}).md`;
			const candidateExists = await this.app.vault.adapter.exists(candidate);
			if (!candidateExists) return candidate;
		}

		throw new Error(`Too many filename collisions for: ${filename}`);
	}
}
