export type TimestampFormat = 'segment' | '30s' | '60s' | 'none';

export interface PlaylistConfig {
	name: string;
	url: string;
	enabled: boolean;
}

export interface TubescribeSettings {
	ytdlpPath: string;
	playlists: PlaylistConfig[];
	outputFolder: string;
	templatePath: string;
	filenameFormat: string;
	syncOnStartup: boolean;
	autoSyncInterval: number; // 0 = disabled, else milliseconds
	preferredLanguages: string;
	includeAutoGenerated: boolean;
	timestampFormat: TimestampFormat;
	createNoteWithoutTranscript: boolean;
	groupByPlaylist: boolean;
}

export const DEFAULT_SETTINGS: TubescribeSettings = {
	ytdlpPath: '',
	playlists: [],
	outputFolder: '1-chaos/external/youtube-transcripts',
	templatePath: '',
	filenameFormat: '{{published}} - {{title}}',
	syncOnStartup: false,
	autoSyncInterval: 0,
	preferredLanguages: 'en,en-US,en-GB',
	includeAutoGenerated: true,
	timestampFormat: 'segment',
	createNoteWithoutTranscript: true,
	groupByPlaylist: false,
};

export interface VideoMetadata {
	id: string;
	title: string;
	url: string;
	uploader: string | null;
	channel_url: string | null;
	upload_date: string | null; // YYYYMMDD from yt-dlp
	duration: number | null; // seconds
	description: string | null;
}

export interface TranscriptSegment {
	startSeconds: number;
	endSeconds: number;
	text: string;
}

export interface TemplateVariables {
	title: string;
	channel: string;
	channel_url: string;
	url: string;
	video_id: string;
	published: string;
	synced: string;
	duration: string;
	playlist: string;
	description: string;
	has_transcript: string;
	transcript: string;
	transcript_raw: string;
}

export interface SyncResult {
	created: number;
	skipped: number;
	errors: number;
	errorDetails: string[];
}
