import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, readdir, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { VideoMetadata } from './types';

const execFileAsync = promisify(execFile);

const CANDIDATE_PATHS = [
	'yt-dlp',
	'/usr/local/bin/yt-dlp',
	'/opt/homebrew/bin/yt-dlp',
];

const METADATA_TIMEOUT = 30_000;
const TRANSCRIPT_TIMEOUT = 60_000;
const MAX_BUFFER = 50 * 1024 * 1024; // 50MB for large playlists

/**
 * Resolve the yt-dlp binary path. If configuredPath is non-empty, validates it.
 * Otherwise tries common locations.
 */
export async function resolveYtdlpPath(configuredPath: string): Promise<string> {
	if (configuredPath) {
		await testYtdlp(configuredPath);
		return configuredPath;
	}

	for (const candidate of CANDIDATE_PATHS) {
		try {
			await testYtdlp(candidate);
			return candidate;
		} catch {
			// Try next candidate
		}
	}

	throw new Error(
		'yt-dlp not found. Install it (e.g. "brew install yt-dlp") or set the path in settings.'
	);
}

/**
 * Test yt-dlp binary by running --version. Returns the version string.
 */
export async function testYtdlp(binaryPath: string): Promise<string> {
	const { stdout } = await execFileAsync(binaryPath, ['--version'], {
		timeout: 10_000,
	});
	return stdout.trim();
}

/**
 * Fetch playlist video metadata using --flat-playlist --dump-json.
 * Returns basic metadata per video (some fields may be null).
 */
export async function fetchPlaylistMetadata(
	binaryPath: string,
	playlistUrl: string
): Promise<VideoMetadata[]> {
	const { stdout } = await execFileAsync(
		binaryPath,
		['--flat-playlist', '--dump-json', playlistUrl],
		{ timeout: METADATA_TIMEOUT, maxBuffer: MAX_BUFFER }
	);

	const videos: VideoMetadata[] = [];
	const lines = stdout.trim().split('\n');

	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			const data = JSON.parse(line);
			videos.push({
				id: data.id,
				title: data.title || 'Untitled',
				url: `https://www.youtube.com/watch?v=${data.id}`,
				uploader: data.uploader || null,
				channel_url: data.channel_url || null,
				upload_date: data.upload_date || null,
				duration: data.duration || null,
				description: data.description || null,
			});
		} catch {
			// Skip malformed lines
		}
	}

	return videos;
}

/**
 * Fetch full metadata for a single video using --dump-json.
 * This gives complete data including uploader, upload_date, description.
 */
export async function fetchVideoMetadata(
	binaryPath: string,
	videoId: string
): Promise<VideoMetadata> {
	const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
	const { stdout } = await execFileAsync(
		binaryPath,
		['--dump-json', '--skip-download', videoUrl],
		{ timeout: METADATA_TIMEOUT, maxBuffer: MAX_BUFFER }
	);

	const data = JSON.parse(stdout);
	return {
		id: data.id,
		title: data.title || 'Untitled',
		url: videoUrl,
		uploader: data.uploader || data.channel || null,
		channel_url: data.channel_url || data.uploader_url || null,
		upload_date: data.upload_date || null,
		duration: data.duration || null,
		description: data.description || null,
	};
}

/**
 * Download transcript for a video. Returns raw VTT string or null if unavailable.
 */
export async function downloadTranscript(
	binaryPath: string,
	videoUrl: string,
	languages: string[],
	includeAutoGenerated: boolean
): Promise<string | null> {
	const tempDir = await mkdtemp(join(tmpdir(), 'tubescribe-'));

	try {
		const args = [
			'--skip-download',
			'--write-sub',
			'--sub-lang', languages.join(','),
			'--sub-format', 'vtt',
			'--convert-subs', 'vtt',
			'-o', join(tempDir, '%(id)s.%(ext)s'),
			videoUrl,
		];

		if (includeAutoGenerated) {
			args.splice(1, 0, '--write-auto-sub');
		}

		await execFileAsync(binaryPath, args, {
			timeout: TRANSCRIPT_TIMEOUT,
			maxBuffer: MAX_BUFFER,
		});

		// Find the .vtt file
		const files = await readdir(tempDir);
		const vttFile = files.find((f) => f.endsWith('.vtt'));

		if (!vttFile) {
			return null;
		}

		return await readFile(join(tempDir, vttFile), 'utf-8');
	} catch {
		// No subtitles available or yt-dlp error
		return null;
	} finally {
		await rm(tempDir, { recursive: true, force: true }).catch(() => {});
	}
}
